AWSTemplateFormatVersion: 2010-09-09
Description: quantummaid tutorials lambda function source bucket

Resources:
  SourceBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: Private
      BucketName: !Sub ${AWS::StackName}
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
          - Status: Enabled
            ExpirationInDays: 2
